# Generated by Django 4.2.6 on 2023-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapi', '0002_bodypoint_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publication_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BodyPoint',
        ),
    ]
