# Generated by Django 4.2.6 on 2023-10-14 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseapi', '0003_book_delete_bodypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mediapipe_points', models.JSONField()),
            ],
        ),
    ]
